# Generated by Django 3.2.25 on 2024-06-21 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aroma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название аромата')),
            ],
            options={
                'verbose_name': 'Аромат',
                'verbose_name_plural': 'Ароматы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('volume', models.PositiveSmallIntegerField(verbose_name='Объем')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('sex', models.CharField(choices=[('F', 'женский'), ('M', 'мужской')], max_length=1, verbose_name='Пол')),
                ('type', models.CharField(choices=[('EDT', 'Туалетная вода'), ('EDP', 'Парфюмерная вода'), ('ES', 'Одеколон'), ('PARFUM', 'Духи'), ('EF', 'Вода (Eau Fraiche)')], max_length=10, verbose_name='Тип продукта')),
            ],
            options={
                'verbose_name': 'Парфюм',
                'verbose_name_plural': 'Парфюм',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('url', models.URLField(unique=True, verbose_name='Ссылка')),
                ('logo', models.ImageField(upload_to='', verbose_name='Лого')),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PerfumeVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('evaluation', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Оценка')),
                ('url_to_perfume', models.URLField(verbose_name='Ссылка на продукт')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.perfume')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.vendor')),
            ],
            options={
                'verbose_name': 'Продукт - продавец',
                'verbose_name_plural': 'Продукты - продавцы',
            },
        ),
        migrations.CreateModel(
            name='PerfumeAroma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aroma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.aroma')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfume.perfume')),
            ],
            options={
                'verbose_name': 'Парфюм - аромат',
                'verbose_name_plural': 'Парфюм - ароматы',
            },
        ),
        migrations.AddField(
            model_name='perfume',
            name='aromas',
            field=models.ManyToManyField(related_name='aromas', through='perfume.PerfumeAroma', to='perfume.Aroma'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='vendors',
            field=models.ManyToManyField(related_name='vendors', through='perfume.PerfumeVendor', to='perfume.Vendor'),
        ),
    ]
