# Generated by Django 3.2.25 on 2024-06-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='aromas',
            field=models.ManyToManyField(through='perfume.PerfumeAroma', to='perfume.Aroma'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='vendors',
            field=models.ManyToManyField(through='perfume.PerfumeVendor', to='perfume.Vendor'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='sex',
            field=models.CharField(choices=[('M', 'мужской'), ('F', 'женский')], max_length=1, verbose_name='Пол'),
        ),
    ]
