# Generated by Django 3.2.25 on 2024-06-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='sex',
            field=models.CharField(choices=[('M', 'мужской'), ('F', 'женский')], max_length=1, verbose_name='Пол'),
        ),
    ]
