# Generated by Django 3.2.25 on 2024-06-21 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0002_alter_perfume_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='sex',
            field=models.CharField(choices=[('F', 'женский'), ('M', 'мужской')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='perfumevendor',
            name='perfume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfume', to='perfume.perfume'),
        ),
        migrations.AlterField(
            model_name='perfumevendor',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='perfume.vendor'),
        ),
    ]
